name: Build Sandbox

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

concurrency:
  group: build-sandbox-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - run: npm ci
      - name: Restore sandbox build cache
        uses: actions/cache@v3
        id: sandbox-cache
        with:
          path: sandboxrpc/target
          key: ${{ runner.os }}-sandboxrpc-${{ hashFiles('sandboxrpc/src/**', 'sandboxrpc/Cargo.*') }}
          restore-keys: |
            sandboxrpc-
      - name: Build sandbox
        if: steps.sandbox-cache.outputs.cache-hit != 'true'
        run: npm run build:sandbox
      - name: Upload sandbox binary
        uses: actions/upload-artifact@v4
        with:
          name: sandboxrpc-binary
          path: sandboxrpc/target/debug/sandboxrpc