name: Build Sandbox

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  build-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
      - run: npm ci
      - name: Ensure sandboxrpc target folder exists
        run: mkdir -p sandboxrpc/target
      - name: Restore sandbox build cache
        uses: actions/cache@v3
        id: sandbox-cache
        with:
          path: sandboxrpc/target
          key: sandboxrpc-${{ hashFiles('sandboxrpc/**') }}
          restore-keys: |
            sandboxrpc-
      - name: Build sandbox
        if: steps.sandbox-cache.outputs.cache-hit != 'true'
        run: npm run build:sandbox
