name: Deploy Treasury Factory contract

on:
  workflow_dispatch: # This allows manual triggering
  push:
    branches:
      - main
      - staging
    paths:
      - 'treasury-factory/**'
      - 'web4/**'

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: "treasury-factory.near"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
      - name: Deploy
        run: |
          cargo build # TODO: Remove this step once https://github.com/near/cargo-near/issues/287 is fixed
          cargo near deploy build-non-reproducible-wasm  "${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}" \
            without-init-call \
            network-config mainnet \
            sign-with-plaintext-private-key \
            --signer-public-key "${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}" \
            --signer-private-key "${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}" \
            send
        working-directory: ./treasury-factory
