name: Deploy Rust web4 contract

on:
  push:
    branches: [main]
  pull_request:
      branches: [main]
jobs:
  test:
    uses: ./.github/workflows/test-web4-contract.yml

  deploy:
    name: Deploy to production
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
#          - treasury-devdao.near
          - infinex.near
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
      - name: Deploy to ${{ matrix.environment }}
        run: |
          cargo near deploy --no-docker "${{ vars.NEAR_TREASURY_WEB4_ACCOUNT_ID }}" \
            without-init-call \
            network-config "${{ vars.NEAR_TREASURY_WEB4_NETWORK }}" \
            sign-with-plaintext-private-key \
              --signer-public-key "${{ vars.NEAR_TREASURY_WEB4_PUBLIC_KEY }}" \
              --signer-private-key "${{ secrets.NEAR_TREASURY_WEB4_PRIVATE_KEY }}" \
            send
        working-directory: ./web4/treasury-web4
        env:
          NEAR_TREASURY_WEB4_ACCOUNT_ID: ${{ matrix.environment }}
