name: Deploy Treasury Factory contract

on:
  workflow_dispatch: # This allows manual triggering
  push:
    branches:
      - main
    paths:
      - 'treasury-factory/**'
      - 'web4/**'

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: "treasury-factory.near"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Rust 1.86
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.86
      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh
      - name: Deploy
        run: |
          if [ -z "${{ secrets.PIKESPEAK_API_KEY }}" ]; then
            echo "Error: PIKESPEAK_API_KEY secret is not set."
            exit 1
          fi
          if [ -z "${{ secrets.POSTHOG_API_KEY }}" ]; then
            echo "Error: POSTHOG_API_KEY secret is not set."
            exit 1
          fi
          export PIKESPEAK_API_KEY="${{ secrets.PIKESPEAK_API_KEY }}""
          export POSTHOG_API_KEY="${{ secrets.POSTHOG_API_KEY }}"

          cargo near deploy build-reproducible-wasm  "${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}" \
            without-init-call \
            network-config mainnet \
            sign-with-plaintext-private-key \
            --signer-public-key "${{ vars.NEAR_SOCIAL_ACCOUNT_PUBLIC_KEY }}" \
            --signer-private-key "${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}" \
            send
        working-directory: ./treasury-factory
