name: Install Dependencies

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      # Restore cache for both node_modules and Playwright browsers
      - name: Restore node_modules and Playwright browser cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: deps-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-

      # Install dependencies and Playwright
      - name: Install dependencies and Playwright
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install

      # Save to cache (in case it was a cache miss)
      - name: Cache node_modules and Playwright browsers
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: deps-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
