name: Playwright Tests - System updates
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: system-updates-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests-system-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Build project
        run: npm run build
      - name: Restore sandbox build cache
        uses: actions/cache@v3
        id: sandbox-cache
        with:
          path: sandboxrpc/build
          key: sandboxrpc-${{ hashFiles('sandboxrpc/**') }}
          restore-keys: |
            sandboxrpc-
      
      - name: Build sandbox
        if: steps.sandbox-cache.outputs.cache-hit != 'true'
        run: npm run build:sandbox
      - name: Run tests
        run: npx playwright test --project=treasury-testing playwright-tests/tests/system-updates
