name: Playwright Tests - Asset Exchange

on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"

concurrency:
  group: asset-exchange-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests-asset-exchange:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
        project:
          - infinex

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download and extract node_modules
      - name: Download installed dependencies
        uses: actions/download-artifact@v4
        with:
          name: installed-dependencies
          path: ./

      - name: Extract node_modules
        run: tar -xzf installed-dependencies.tar.gz

      - name: Download Playwright browsers
        uses: actions/download-artifact@v4
        with:
          name: playwright-browsers
          path: ./

      - name: Extract Playwright browsers
        run: |
          mkdir -p ~/.cache
          tar -xzf playwright-browsers.tar.gz -C ~/.cache

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Build project
        run: npm run build

      - name: Download sandbox binary
        uses: actions/download-artifact@v4
        with:
          name: sandboxrpc-binary
          path: sandboxrpc/target/debug

      - name: Make sandbox binary executable
        run: chmod +x sandboxrpc/target/debug/sandboxrpc

      - name: Run tests
        id: run-tests # Add an id to this step to reference its outcome
        run: |
          npx playwright test playwright-tests/tests/asset-exchange/proposal-details.spec.js \
            --project=${{ matrix.project }} \
            --shard=${{ matrix.shard }}

      - name: Upload Playwright Test Artifacts (on failure)
        if: failure() && steps.run-tests.outcome == 'failure' # Condition to run only if the run-tests step failed
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts-${{ matrix.project }}-${{ matrix.shard }}.zip # Name of the artifact
          path: | # Paths to include in the artifact
            test-results/
            playwright-report/ # Often contains trace files and HTML reports
          retention-days: 1 # Optional: How long to keep the artifacts
