name: Playwright Tests - Web4

on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: "20"

concurrency:
  group: web4-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests-web4:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
        project:
          - treasury-dashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Download installed dependencies
        uses: actions/download-artifact@v4
        with:
          name: installed-dependencies
          path: ./

      - name: Extract node_modules
        run: tar -xzf installed-dependencies.tar.gz

      - name: Download Playwright browsers
        uses: actions/download-artifact@v4
        with:
          name: playwright-browsers
          path: ./

      - name: Extract browsers
        run: |
          mkdir -p ~/.cache
          tar -xzf playwright-browsers.tar.gz -C ~/.cache

      - name: Build project
        run: npm run build

      - name: Download sandbox binary
        uses: actions/download-artifact@v4
        with:
          name: sandboxrpc-binary
          path: sandboxrpc/target/debug

      - name: Make sandbox executable
        run: chmod +x sandboxrpc/target/debug/sandboxrpc

      - name: Install cargo-near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/cargo-near/releases/latest/download/cargo-near-installer.sh | sh

      - name: Build web4 contract for use in sandbox
        run: |
          cd web4/treasury-web4
          cargo near build non-reproducible-wasm

      - name: Run tests
        id: web4-tests
        run: |
          npx playwright test playwright-tests/tests/web4 \
            --project=${{ matrix.project }} \
            --shard=${{ matrix.shard }}

      - name: Sanitize shard name
        run: echo "SHARD_SAFE=$(echo "${{ matrix.shard }}" | sed 's|/|-|')" >> $GITHUB_ENV

      - name: Upload Playwright Test Artifacts (on failure)
        if: failure() && steps.web4-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-artifacts-web4-${{ matrix.project }}-shard-${{ env.SHARD_SAFE }}.zip
          path: |
            test-results/
            playwright-report/
          retention-days: 1
