name: Playwright Tests - Asset Exchange

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: asset-exchange-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sandbox:
    uses: ./.github/workflows/build_sandbox.yml

  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml

  playwright-tests-asset-exchange:
    runs-on: ubuntu-latest
    needs: [build-sandbox, install-dependencies]
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
        project:
          - treasury-dashboard
          - infinex

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Download and extract node_modules
      - name: Download installed dependencies
        uses: actions/download-artifact@v4
        with:
          name: installed-dependencies
          path: ./

      - name: Extract node_modules
        run: tar -xzf installed-dependencies.tar.gz

      # Download and extract Playwright browsers
      - name: Download Playwright browsers
        uses: actions/download-artifact@v4
        with:
          name: playwright-browsers
          path: ./

      - name: Extract Playwright browsers
        run: |
          mkdir -p ~/.cache
          tar -xzf playwright-browsers.tar.gz -C ~/.cache

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Build project
        run: npm run build

      - name: Download sandbox binary
        uses: actions/download-artifact@v4
        with:
          name: sandboxrpc-binary
          path: sandboxrpc/target/debug

      - name: Make sandbox binary executable
        run: chmod +x sandboxrpc/target/debug/sandboxrpc

      - name: Run tests
        run: |
          npx playwright test playwright-tests/tests/asset-exchange \
            --project=${{ matrix.project }} \
            --shard=${{ matrix.shard }}
