name: Playwright Tests - Asset Exchange

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Prepare Dependencies"]
    types:
      - completed

concurrency:
  group: asset-exchange-${{ github.ref }}
  cancel-in-progress: true

jobs:
  playwright-tests-asset-exchange:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]
        project:
          - treasury-dashboard
          - infinex

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      # Restore both node_modules and Playwright browser binaries
      - name: Restore dependencies and Playwright browsers
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/ms-playwright
          key: deps-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Build project
        run: npm run build

      - name: Restore sandbox build cache
        uses: actions/cache@v3
        with:
          path: sandboxrpc/target
          key: sandboxrpc-${{ runner.os }}-${{ hashFiles('sandboxrpc/src/**', 'sandboxrpc/Cargo.*') }}
          restore-keys: |
            sandboxrpc-${{ runner.os }}-

      - name: Make sandbox binary executable
        run: chmod +x sandboxrpc/target/debug/sandboxrpc

      - name: Run tests
        run: |
          npx playwright test playwright-tests/tests/asset-exchange \
            --project=${{ matrix.project }} \
            --shard=${{ matrix.shard }}
