name: Prepare Dependencies

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: prepare-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-sandbox:
    uses: ./.github/workflows/build_sandbox.yml

  install-dependencies:
    uses: ./.github/workflows/install-dependencies.yml
