name: Deploy Components to Production

on:
  push:
    branches: [main]

jobs:
  deploy-widgets:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_account:
          - environment: treasury-devdao.near
            deploy_command: npm run deploy:devdao
          - environment: treasury-infinex.near
            deploy_command: npm run deploy:infinex
          - environment: treasury-templar.near
            deploy_command: npm run deploy:templar
          - environment: treasury-factory.near
            deploy_command: npm run deploy:treasury-factory
          - environment: widgets.treasury-factory.near
            deploy_command: npm run deploy:widgets
          - environment: bootstrap.treasury-factory.near
            deploy_command: npm run deploy:bootstrap
    environment: ${{ matrix.target_account.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/bos-cli-rs/bos-cli-rs/releases/download/v0.4.1/bos-cli-installer.sh | sh

      - name: Deploy widgets
        run: |
          ${{ matrix.target_account.deploy_command }} -- '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' sign-as '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' network-config mainnet-fastnear sign-with-plaintext-private-key '${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}' send
