name: Deploy Components to Staging

on:
  workflow_dispatch: # This allows manual triggering
  push:
    branches: [staging]

jobs:
  deploy-widgets:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_account:
          - environment: treasury-testing.near
            deploy_command: npm run deploy:testing
          - environment: treasury-testing-infinex.near
            deploy_command: npm run deploy:infinex-testing
          - environment: test-widgets.treasury-factory.near
            deploy_command: npm run deploy:test-widgets
          - environment: test-bootstrap.treasury-factory.near
            deploy_command: npm run deploy:test-bootstrap
    environment: ${{ matrix.target_account.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/bos-cli-rs/bos-cli-rs/releases/download/v0.4.1/bos-cli-installer.sh | sh

      - name: Deploy widgets
        run: |
          ${{ matrix.target_account.deploy_command }} -- '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' sign-as '${{ vars.NEAR_SOCIAL_ACCOUNT_ID }}' network-config mainnet-fastnear sign-with-plaintext-private-key '${{ secrets.NEAR_SOCIAL_ACCOUNT_PRIVATE_KEY }}' send
