# name: Dry-run staging

# on:
#   pull_request:
#     branches: [staging]

# jobs:
#   deploy-widgets:
#     name: Diff from PR
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         target_account:
#           - dry_run_command: npm run dry-run:testing
#           - dry_run_command: npm run dry-run:infinex-testing
#           - dry_run_command: npm run dry-run:test-widgets
#           - dry_run_command: npm run dry-run:test-bootstrap
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         run: |
#           npm ci
#           curl --proto '=https' --tlsv1.2 -LsSf https://github.com/bos-cli-rs/bos-cli-rs/releases/download/v0.3.15/bos-cli-installer.sh | sh

#       - name: Dry-run widgets
#         run: |
#           ${{ matrix.target_account.dry_run_command }}
