name: Test
on:
  workflow_call:

jobs:
  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build web4 html
        run: npm run web4:createrustcontractbundle        
      - run: cargo fmt --check
        working-directory: ./web4/rust_contract/treasury-web4

  code-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --workspace --tests -- --warn clippy::all --warn clippy::nursery
        working-directory: ./web4/rust_contract/treasury-web4

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo test
        run: cargo test
        working-directory: ./web4/rust_contract/treasury-web4
