name: "Test web4 Rust"
on:
  workflow_call: {}
  pull_request:
  push:
    branches:
      - main

jobs:
  code-formatting:
    name: Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: cargo fmt --check
        working-directory: ./web4/treasury-web4

  code-linter:
    name: Code Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo clippy
        run: |
          rustup component add clippy
          cargo clippy --all-features --workspace --tests -- --warn clippy::all --warn clippy::nursery
        working-directory: ./web4/treasury-web4

  build-treasury-factory:
    name: Build Treasury Factory
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo build
        run: cargo near build reproducible-wasm
        working-directory: ./treasury-factory

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run cargo test
        run: cargo test
        working-directory: ./web4/treasury-web4
